Repository RatakondalaArun/tmdb_api, pull requests merged in 2021-03, with the labels that each got.

#28 getImages added for tv in v3
  lib/versions/v3/category/tv.dart
Labels: enhancement

#30 Add missing optional query
  lib/versions/v3/category/search.dart
Labels: bug

#31 Add/missing-method-29
  .gitattributes
  lib/versions/v3/category/tv.dart
  lib/versions/v3/category/tv_seasons.dart
Labels: enhancement, missing feature

#32 release v1.2.6
  CHANGELOG.md
  pubspec.yaml
Labels: enhancement

#33 Release v1.2.6
  .gitattributes
  CHANGELOG.md
  lib/versions/v3/category/search.dart
  lib/versions/v3/category/tv.dart
  lib/versions/v3/category/tv_seasons.dart
  pubspec.yaml
Labels: enhancement
