Repository RatakondalaArun/tmdb_api, pull requests merged in 2022-05, with the labels that each got.

#84 Change tvId type in aggregateCredits to int
  lib/versions/v3/category/tv.dart
Labels: 🐛bug

#85 Add language query to trending
  lib/versions/v3/category/trending.dart
Labels: ✨enhancement

#86 release/v2.1.2
  CHANGELOG.md
  lib/versions/v3/category/trending.dart
  lib/versions/v3/category/tv.dart
  pubspec.lock
  pubspec.yaml
Labels: 🏷release
